### PR TITLE
SOLID principales

### PR DESCRIPTION
**Pull request by thasipablo**
### Feature added

- Added start method
- Create the launcher class in a separated file

### CODE REVIEW

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @thasipablo 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that doesn't have commits and contributions from your partner. This is a pair programming activity, and both students must commit meaningfully to this branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by frank1738 — COMMENTED** [review]
Hi @thasipablo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a pair programming project with one contributor. Kindly get your partner to contribute to the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Ibizugbe — COMMENTED** [review]
Hi @thasipablo 👋🏼👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have contributions from your learning partner. kinldly reach out to your learning partner and work with him. if there's nothing more to be done, kindly checkout to a new branch and work at fresh actively with your partner as this milestone is meant to be a pair programing activity and can't be reviewed if your learning partner hasn't actively contributed. If you are having issues with your partner, kindly report to the student success team and if granted an approval to work solo, kindly upload it on your PR description😉.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @thasipablo 👋, 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project in which your coding partner @Nessrine88 only made changes to the README and LICENSE files. This doesn't count as a contribution as your partner didn't contribute to implementing project features. I would advise you to close this pull request, create another one and properly implement the features alongside your partner. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
